added CD details
devopsdojoconsortium/playbooks pull request #3
Opened 2019-04-27 02:59 UTC by bigben79

added 5 principles of CD to the DevOps section

2019-04-27 10:48 UTC, bdfinst requested changes
May want to remove the "to"

2019-04-27 10:48 UTC, bdfinst commented on devops/README.md
> +  2) Reduce Batch Sizes and deploy to frequently
Grammar with "to"

2019-04-27 14:08 UTC, bigben79 commented on devops/README.md
> +  2) Reduce Batch Sizes and deploy to frequently
@bdfinst Updated my grammar.
```suggestion
  2) Reduce Batch Sizes and deploy frequently
```

2019-05-02 12:24 UTC, bdfinst approved these changes

2019-05-02 12:24 UTC, merged